"""Initial migration

Revision ID: eed3c356bddd
Revises: 
Create Date: 2026-07-03 13:07:33.473733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed3c356bddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('workspace', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_index(op.f('ix_datasets_workspace'), 'datasets', ['workspace'], unique=False)
    op.create_table('distillation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('eta', sa.String(length=50), nullable=False),
    sa.Column('gpu_hours', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('workspace', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distillation_jobs_created_at'), 'distillation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_distillation_jobs_id'), 'distillation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_distillation_jobs_user_id'), 'distillation_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_distillation_jobs_workspace'), 'distillation_jobs', ['workspace'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('benchmark', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_job_id'), 'evaluations', ['job_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_artifacts_id'), 'model_artifacts', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_model', sa.String(length=100), nullable=False),
    sa.Column('flavor_profile', sa.String(length=100), nullable=False),
    sa.Column('knowledge_blend', sa.Integer(), nullable=False),
    sa.Column('reasoning_style', sa.Integer(), nullable=False),
    sa.Column('tool_use', sa.Integer(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('safety', sa.Integer(), nullable=False),
    sa.Column('hardware_budget', sa.Integer(), nullable=False),
    sa.Column('deployment_target', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('workspace', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_created_at'), 'recipes', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_index(op.f('ix_recipes_workspace'), 'recipes', ['workspace'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('workspace', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_workspace'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_created_at'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_model_artifacts_id'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_evaluations_job_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_distillation_jobs_workspace'), table_name='distillation_jobs')
    op.drop_index(op.f('ix_distillation_jobs_user_id'), table_name='distillation_jobs')
    op.drop_index(op.f('ix_distillation_jobs_id'), table_name='distillation_jobs')
    op.drop_index(op.f('ix_distillation_jobs_created_at'), table_name='distillation_jobs')
    op.drop_table('distillation_jobs')
    op.drop_index(op.f('ix_datasets_workspace'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
